{% set name = "cerbere" %}
{% set version = "3.0.0.post39" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/cerbere-{{ version }}.tar.gz
  sha256: 7aaf6b60d4d954fd0a4952bf3a5d92be6fa9eb982c64a0194aa429b799b221f0

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.10,<4.0
    - poetry-core >=1.0.0
    - poetry-dynamic-versioning >=1.0.0,<2.0.0
    - pip
  run:
    - python >=3.10.0,<4.0.0
    - xarray <=2024.1.1
    - shapely >=2.0.6,<3.0.0
    - pyyaml >=6.0.2,<7.0.0
    - scipy >=1.14.1,<2.0.0
    - h5netcdf >=1.3.0,<2.0.0
    - dask-core >=2024.8.2,<2025.0.0
    - cftime >=1.6.4,<2.0.0

test:
  imports:
    - cerbere
  commands:
    - pip check
  requires:
    - pip

about:
  summary: A python API to manipulate spatial and temporal observations, compatible with many existing formats, normalizing and typing the representation of these observations, following Climate and Forecast (CF) convention and data model.
  license: GPL-3.0-or-later
  license_file: LICENSE.txt
  home: https://gitlab.ifremer.fr/cerbere/cerbere/
  doc_url: https://cerbere.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - criou-cg
    - jfpiolle
    - marie59
