{% set python_min = '3.10.0' %}
{% set name = "cerbere" %}
{% set version = "3.1.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://gitlab.ifremer.fr/cerbere/cerbere/-/archive/{{ version }}/cerbere-{{ version }}.tar.gz
  sha256: 24b330d271f2a1126cbfff70072d42978c80c2f543f86ce0ac54679c0048705d

build:
  noarch: python
  script: POETRY_DYNAMIC_VERSIONING_BYPASS={{ version }} {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - poetry-core >=1.0.0
    - poetry-dynamic-versioning >=1.0.0,<2.0.0
    - pip
  run:
    - python >={{ python_min }},<3.11
    - importlib-metadata >=8.5.0,<8.6.1
    - xarray >=2024.10.0,<2025.1.0
    - shapely >=2.0.6,<3.0.0
    - pyyaml >=6.0.2,<7.0.0
    - scipy >=1.14.1,<2.0.0
    - h5netcdf >=1.3.0,<2.0.0
    - dask >=2024.11.0,<2025.1.0
    - cftime >=1.6.4,<2.0.0

test:
  imports:
    - cerbere
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  summary: A python API to manipulate spatial and temporal observations, compatible with many existing formats, normalizing and typing the representation of these observations, following Climate and Forecast (CF) convention and data model.
  license: LGPL-3.0-only
  license_file: LICENSE.md
  home: https://gitlab.ifremer.fr/cerbere/cerbere/
  doc_url: https://cerbere.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - cso2943
    - criou-cg
    - erwanbodere
    - jfpiolle
    - marie59
