{% set name = "cerbere" %}
{% set version = "2.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://gitlab.ifremer.fr/cerbere/cerbere/-/archive/V{{ version }}/cerbere-V{{ version }}.tar.gz
  sha256: f127d699086596c7434a8ab5b5562bd8f02973395d3e2d730e9dab01dbcfae51

build:
  number: 0
  noarch: python
  script_env:
    - POETRY_DYNAMIC_VERSIONING_BYPASS={{ version }}
  script:
    - {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.8
    - pip
    - poetry-core >=1.0.0
    - poetry-dynamic-versioning
  run:
    - python >=3.8
    - pyyaml >=5.3
    - netcdf4 >=1.5
    - scipy >=1.5
    - shapely >=1.7
    - xarray >=2022.3.0

test:
  imports:
    - cerbere

about:
  home: https://gitlab.ifremer.fr/cerbere/cerbere
  license: GPL-3.0-or-later
  license_file: LICENSE.txt
  summary: cerbere provides a unified python API to manipulate any type of spatio-temporal observations
  description: |
    cerbere provides a unified python API to manipulate any type of spatio-temporal observations,
    which can be read from many existing storage formats using the same set of functions.
    It also provides classes for specific types of observation features.

extra:
  recipe-maintainers:
    - marie59
